# Generated by Django 2.1.2 on 2018-11-28 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presents',
            options={'verbose_name_plural': 'Presents'},
        ),
        migrations.AddField(
            model_name='presents',
            name='given_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
