# Generated by Django 2.1.2 on 2018-11-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_auto_20181128_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presents',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='presents',
            name='type_input',
            field=models.CharField(default='Purchased', max_length=200),
            preserve_default=False,
        ),
    ]
