# Generated by Django 2.1.2 on 2018-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0003_auto_20181129_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presents',
            old_name='description',
            new_name='memento',
        ),
        migrations.AddField(
            model_name='presents',
            name='given_to',
            field=models.CharField(default='Present', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presents',
            name='present',
            field=models.TextField(default='Present'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presents',
            name='type_input',
            field=models.CharField(default='Purchased', max_length=200),
        ),
    ]
