# Generated by Django 2.1.2 on 2018-11-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0004_auto_20181129_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presents',
            name='present',
        ),
    ]
