# Generated by Django 2.1.2 on 2018-11-29 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personbooks',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='personbooks',
            name='firstName',
            field=models.CharField(default='Present', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personbooks',
            name='lastName',
            field=models.CharField(default='Present', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personbooks',
            name='relation',
            field=models.TextField(default='Friend'),
            preserve_default=False,
        ),
    ]
