# Generated by Django 2.1.2 on 2018-11-28 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearbook', '0002_remove_yearbooks_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearbooks',
            name='title',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only characters 0-9 are allowed.'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
